#!/bin/bash

# temp hack
rm /etc/security/limits.d/cassandra.conf 

# run confd
export CASSANDRA_SETTINGS_MAXHEAPSIZE=${CASSANDRA_SETTINGS_MAXHEAPSIZE:-512M}
export CASSANDRA_SETTINGS_HEAPNEWSIZE=${CASSANDRA_SETTINGS_HEAPNEWSIZE:-50M}
export CASSANDRA_SETTINGS_CLUSTERNAME=${CASSANDRA_SETTINGS_CLUSTERNAME:-cass_01}
export CASSANDRA_SETTINGS_LISTENADDRESS=${CASSANDRA_SETTINGS_LISTENADDRESS:-" "}
export CASSANDRA_SETTINGS_RPCADDRESS=${CASSANDRA_SETTINGS_RPCADDRESS:-" "}
export CASSANDRA_SETTINGS_BROADCASTADDRESS=${HOST_IP:-"172.17.8.101"}
export CASSANDRA_SETTINGS_SEEDS=${CASSANDRA_SETTINGS_SEEDS:-"127.0.0.1"}

/usr/local/bin/confd -backend env -prefix=/cassandra -verbose=true -onetime

# start cassandra
/usr/sbin/cassandra -f